version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14.17.0
    steps:
      - checkout
      - run: npm install
      - save_cache:
          key: "npm-packages"
          paths:
            - /src/node_modules
      - run: npm run lint
  test:
    docker:
      - image: circleci/node:14.17.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm-packages"
      - run: npm install
      - run: npm run test
  analyze:
    docker:
      - image: circleci/node:14.17.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm-packages"
      - run: npm audit
      - run: npm audit fix
      - run: npm audit fix --force

workflows:
  my_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
